# Generated by Django 4.0.4 on 2022-04-15 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='person',
            new_name='periodo',
        ),
    ]
